Metric labels do not include hostname when two queries are used
Checkmk/grafana-checkmk-datasource pull request #225
Opened 2023-11-20 13:14 UTC by lpetrora

This change adds a custom label input box and allows the user to customize the labels. It corresponding filter is created, these variables are available:
* $filter_site: Site name
* $filter_host_name: Host name
* $filter_host_in_group: Group containing the host
* $filter_service: Service name
* $filter_service_in_group: Group containing the service

$label is always available and contains the original label sent by Checmk.

CMK-15138

2023-11-21 16:04 UTC, BenediktSeidl requested changes
changing the label triggers a api call to checkmk, although it is not really needed as we already have all the data we need. can you give it a try to see if you can accomplish the updating of the lables without triggering a new api request to checkmk?
i fear we would have to change quite a lot of the current architecture, but maybe it's doable?

2023-11-22 14:09 UTC, lpetrora commented on src/ui/QueryEditor.tsx
> +      <Alert title="Variables on custom label" severity="info">
I added a toggle button witch displays a popup

![image](https://github.com/Checkmk/grafana-checkmk-datasource/assets/29212725/c51ab7c3-4091-4af5-9599-517a2f11fdc6)

2023-11-22 14:09 UTC, lpetrora commented on src/backend/rest.ts
> -    range.from.set('milliseconds', 0);
Yes, it was an accident

2023-11-22 14:13 UTC, lpetrora commented on src/ui/components.tsx
> +  const debouncedOnChange = React.useMemo(
Yes, the idea is to refactor Filter to use GenericField and simplify the code

2023-11-27 08:55 UTC, lpetrora commented on src/utils.ts
> +        .replace(createRegexp(label.ORIGINAL), metric.title)
I modified it and now we use  getTemplateSrv. It allows us to use query parameters (filters) and Grafana's variables for labels names

2023-11-28 07:09 UTC, BenediktSeidl reviewed
regarding the "change label without backend request":

this is where the request is triggered:
https://github.com/Checkmk/grafana-checkmk-datasource/blob/8c2a87a5b020f95056ea57f84de7a3daa94653be/src/ui/QueryEditor.tsx#L48-L55

this is the new url to the docs, the old one no longer works:
https://react.dev/reference/react/useState#storing-information-from-previous-renders

i thought: we could check what parts of the request spec changed, and if only the label changed we call `onChange` only and if we detect that parts of the filter changed, we  call `onRunQuery`.

maybe we should also think about a better idea than this JSON.stringify thing, but this is a quest for another pr.

2023-11-30 07:34 UTC, BenediktSeidl commented
> regarding the "change label without backend request":

as you already mentioned my last idea does not work. i looked at the code again, and maybe my next idea could work: 
we could remember the last query, and the last query result in this function:

https://github.com/Checkmk/grafana-checkmk-datasource/blob/main/src/DataSource.ts#L30-L35

and if they current query is the same as the last query (minus the label change of course) we could use the old result and just interpolate the changed label.

but this feels a bit hacky. probably it does not work at all, because the time range is relative, so we will get a changed timerange with the label change, so the queries differ...

maybe the whole idea of saving one http request is a premature optimization? we can skip it for now, see how everything works out and come back to this idea if we see that its really necessary.

sorry about the confusion.

2023-11-30 14:59 UTC, BenediktSeidl approved these changes

2023-12-01 07:42 UTC, merged